name: "Composite Action Test with Secrets"

description: "Run composite action with secrets as input parameter"

inputs:
  thisdoesnotwork:
    description: 'abra-cadabra web services'
    type: boolean
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: echo secret
      if: $ {{ inputs.thisdoesnotwork == 'true' }} 
      shell: bash
      run: |
        echo "blah blah"

    - name: echo secret
      shell: bash
      run: |
        echo "thisdoesnotwork=" ${{ inputs.thisdoesnotwork }}
        echo Hi ${{ env.AWS_KEY }}