name: "Composite Action Test with Secrets"

description: "Run composite action with secrets as input parameter"

inputs:
  show-the-secret:
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: echo secret
      shell: bash
      run: |
        if [[ "${{inputs.show-the-secret}}" == 'true' ]]; then
          echo Hi ${{ env.AWS_KEY }}
        else 
          echo "Hello world"
        fi